# Generated by Django 3.0 on 2020-03-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_ureg'),
    ]

    operations = [
        migrations.CreateModel(
            name='oreg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('shname', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=20)),
                ('rno', models.IntegerField()),
                ('lmark', models.CharField(max_length=20)),
                ('cno', models.IntegerField()),
                ('uname', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=20)),
                ('status', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('uname', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=20)),
                ('oid', models.IntegerField(default=0)),
            ],
        ),
    ]
