# Generated by Django 3.0 on 2020-03-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.IntegerField()),
                ('sid', models.IntegerField()),
                ('oid', models.IntegerField(default=1)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.IntegerField()),
                ('st', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='vegdet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vegname', models.CharField(max_length=20)),
                ('category', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('image', models.FileField(upload_to='file')),
                ('des', models.CharField(max_length=50)),
                ('stock', models.CharField(max_length=20)),
                ('status', models.CharField(default='', max_length=20)),
                ('oid', models.IntegerField(default=0)),
            ],
        ),
    ]
